### ISSUE TITLE
Allowing the uploader to be inside a form

### ISSUE THREAD

**Issue by ncri** [waynehoover/s3_direct_upload#201]
I removed the need for the uploader to be inside its own form. That means you can now use it inside a form. That makes its usage much nicer in our projects. So far the helper is still called s3_uploader_form and it's used in almost the same way, the only difference is you need to add a data url to your s3 bucket:

    s3_uploader_form uploader_options do
      file_field_tag(:file, data: { url: "your/s3/url/including/bucket/" })
    end

Instead of a form it simply generates a div containing the needed form fields. 
Also note that if used inside a form, the uploader fields are not submitted.
The helper should be renamed to s3_uploader I think.

Here is my fork, the branch is called without_form:

https://github.com/ncri/s3_direct_upload/tree/without_form

**Comment by ncri** [comment]
We found in our project that it's better to submit the form separately from the upload(s). The user can upload one or more files (creating polymorphic attachment records in the db after upload), and then submit the form. That works very well, but we need to regularly run a rake task that cleans out uploads which don't have a rails model object attached to them. Those orfants can exist if a "new" form is not submitted after file upload. To connect the uploaded file's polymorphic attachments to their newly created model object, we add a hidden field "attachment_ids" to the model form, which is then used to assign already uploaded attachments to the newly created model in an after create callback.

**Comment by chaupt** [comment]
Thanks @ncri. We're doing something similar at this point. I've got working a combined form that can do the juggling to associate the separate upload model with its parent and that seems to be working nicely. I added one more tweak to my fork that includes a client-side validation callback option that can trigger before the s3 uploads can start, so we have more options for interacting with the workflow.

**Comment by thomasjoyce** [comment]
i was wondering what do other folks do once the image files are uploaded to S3 directly, do you trigger some sort of process to crop and resize the images after the upload process is done in s3? 

I'm trying to figure out what are the best option route to resize the original images - like small, medium, large, original once it is in S3? I'm currently using heroku so using the direct upload to S3 works quite well bypassing heroku but once it is in s3, is there a way to trigger a process to resize or crop the image directly in S3 bypassing heroku server process? 

Any tips or pointer on this? thanks ;- )

**Comment by ncri** [comment]
Yes, we are using Minimagick to create various versions of the image after upload, in a background process. We implemented it ourselves, but there are also gems like paperclip and carrierwave helping you with this.

**Comment by thomasjoyce** [comment]
nice. ;-) thanks for the tips. actually Minimagick seems to work perfectly since the others ones i was using was hogging up memory on my server. 

any suggestions on what type of background process in S3  will be use to run to trigger the  resize  of the original images? currently i'm using AWS S3 for the upload but i notice AWS Simple Queue Service or Amazon Simple Workflow Service will work for background process. By any chance do you have any recomendations on any open source rails gem that would fit perfectly as background process to trigger the minimagick to do resizing? 

thanks again for your helpful tips @ncri  :- )

**Comment by ncri** [comment]
I haven't used AWS Simple Queue Service or Amazon Simple Workflow Service. We use sidekiq with redis for background jobs. Works really well.

**Comment by thomasjoyce** [comment]
great. i will try those out. thanks again for the helpful tips :- ) luv the github community :- )

**Comment by JacobEvelyn** [comment]
@waynehoover would there be interest in merging this into the codebase? This would be extremely useful for us.

**Comment by ncri** [comment]
Yes, I think so too, although we should probably do some renaming and refactoring as mentioned earlier. Also it might be useful to have the old behavior included. Anyway, we use this branch now in a big production app for a few month and haven't had any issues...

**Comment by JacobEvelyn** [comment]
Thanks for the update, and agreed on the renaming/refactoring you mentioned earlier.

**Comment by waynehoover** [comment]
Feel free to submit a pull based on that branch, would totally merge it in.

**Comment by ncri** [comment]
Okay, I'll see that I can tidy it up a bit and possibly make it backwards compatible - not sure yet if that works out though as the js has changed quite a bit. 

I might need a while, as I'm quite busy with other things currently... Of course you are all welcome to help and work on this on your own branches... ;-)

**Comment by chrisyeung1121** [comment]
+1, wondering what 's the status of this update!

**Comment by ncri** [comment]
Haven't got a chance yet to takle this. But I'll see if I can do it in the next one or two weeks.

**Comment by javvarcar** [comment]
+1 for this solution

**Comment by ncri** [comment]
Okay, I have cleaned up the code and readme here in this old PR:

https://github.com/waynehoover/s3_direct_upload/pull/192

@waynehoover: would be great if you could merge this!

**Comment by waynehoover** [comment]
This looks good. I have merged it into master.

**Comment by ncri** [comment]
Thanks. We should mention in the readme that one needs to supply data: { url: s3_uploader_url } to the file_field, where s3_uploader_url is a helper from s3_direct_upload. It has one optional parameter allowing to use a non ssl url (ssl is true by default). Also one can supply the url directly if needed, without using the helper. 

But thinking about it, I think we should make the helper not require the block with the file field. It can be hidden inside the helper. So why not simply allowing to use the helper like this:

      s3_uploader uploader_options

And a parameter file_field_tag_options could be optionally supplied in uploader_options?
What do you think?

**Comment by waynehoover** [comment]
@ncri that sounds good to me. Do you want to open a new PR with updated readme and code?
