### ISSUE TITLE
Policy Condition failed: ["starts-with", "$utf8", ""]

### ISSUE THREAD

**Issue by onurkucukkece** [waynehoover/s3_direct_upload#221]
I used new syntax and tried to add it as a field but I'm getting this error right before upload completes

    Invalid according to Policy: Policy Condition failed: ["starts-with", "$utf8", ""]

    <%= s3_uploader id: "s3-uploader"  do %>
        <%= file_field_tag :file, multiple: true, data: { url: s3_uploader_url } %>
    <% end %>

**Comment by waynehoover** [comment]
This should be fixed now with https://github.com/waynehoover/s3_direct_upload/pull/223
