### ISSUE TITLE
Undefined url in IE9

### ISSUE THREAD

**Issue by ilyakatz** [waynehoover/s3_direct_upload#229]
This change introduces a problem in IE9 and below - after file is uploaded, the url is not constructed properly - the base url is `undefined`

https://github.com/waynehoover/s3_direct_upload/commit/e4ab3a5bce4c5fa02b04c52ba12560d2d93b01aa#diff-3e2d84438e9bd32d7d3af2865f569690L141

@ncri do you remember the context of this change

```diff
-      domain                 = $uploadForm.attr('action')
+      domain                 = $uploadForm.find('input[type=file]').data('url')
```

**Comment by ncri** [comment]
Did you set the the files input's data-url ?

**Comment by ilyakatz** [comment]
yes, I saw that it is an option but it's not specified anywhere in the docs. So I figured it wasn't intentional. Also, it doesn't seem optimal to add duplicate configuration configured it would need to be updated in all places where this JS file is used

**Comment by ncri** [comment]
Oh, i thought the docs were updated, odd, need to check. It's not optional, its required. Part of a bigger pull request I made a year ago or so.

**Comment by ncri** [comment]
Check these:

https://github.com/waynehoover/s3_direct_upload/pull/192
https://github.com/waynehoover/s3_direct_upload/issues/201

**Comment by ilyakatz** [comment]
You're right, I see it's missing. Ok, will close the issue. Thank you!

**Comment by ncri** [comment]
But you are right, we need to improve the readme.
