### ISSUE TITLE
issues with master

### ISSUE THREAD

**Issue by mcfiredrill** [waynehoover/s3_direct_upload#235]
I can't get master to work. I noticed the `<form>` has been changed to a `<div>`, so I changed my file_field_tag to have a data url attribute, like the readme says you should do:

```
  <%= s3_uploader_form callback_url: model_url, callback_param: "model[image_url]", id: "s3-uploader" do %>        
    <%= file_field_tag :file, multiple: true, data: { url: s3_uploader_url } %>                                    
  <% end %>                                                                                                        
```

The uploader is just POSTing my rails app at the current url when I try to add a file. No request is made to the S3 URL.

Am I doing something wrong ? Is anyone else on master ?

**Comment by mcfiredrill** [comment]
It looks like in jquery-file-upload the upload url is set by the `action` attribute.
https://github.com/blueimp/jQuery-File-Upload/blob/master/js/jquery.fileupload.js#L584

But in master the the action attribute was removed in this commit, I'm not sure why?
https://github.com/waynehoover/s3_direct_upload/commit/e4ab3a5bce4c5fa02b04c52ba12560d2d93b01aa#diff-98fcf18bb8f0556479337cf71e97dc1fL5

So in my case at least, that falls back to using `location.href` for the url to POST to.

Again, unless I'm using the library in a different way from everyone else, I think the `action` parameter should be added back.

**Comment by mcfiredrill** [comment]
Hmm even if the `action` attribute is present, it still won't work since `options.form` is undefined here.
https://github.com/blueimp/jQuery-File-Upload/blob/master/js/jquery.fileupload.js#L579

This is because the `<form>` was changed to a `<div>`, I'm not sure why though. https://github.com/waynehoover/s3_direct_upload/commit/f2180b006d19514f7bbd27cc7c95050b7656fd74
/cc @ncri any chance you could help me out here? :sweat_smile:

**Comment by ncri** [comment]
Well, the form was removed, because it allows the uploader itself to be in another form. It should work fine if you just set the data-url of the file field tag and follow the steps in the readme. Not sure what `location.href` you are meaning. Do you have some example code? Hard to tell what's going wrong without.

**Comment by mcfiredrill** [comment]
@ncri Thanks for getting back to me.
That all makes sense now.
So does it still work standalone, as not part of any other form?
I have a pretty standard setup, following the README.

```
      <%= s3_uploader_form callback_url: tracks_url(format: :js),                                                                                     
                           callback_param: "track[audio_file_name]",                                                                                  
                           key_starts_with: "",                                                                                                                                  key: "${filename}",                                                                                                        
                           id: "track-uploader" do %>                                                                                                 
      <%= file_field_tag :file, multiple: true, data: { url: s3_uploader_url } %>                                                                     
      <div id="dropzone" class="drop-fade well">Drop files here</div>                                                                                 
    <% end %>                                                                                                                                         
    <div id="status"></div>                                                                                                                               <script id="template-upload" type="text/x-tmpl">                                                                                                  
      <div id="file-{%=o.unique_id%}" class="upload">                                                                                                 
        {%=o.name%}                                                                                                                                   
        <div class="progress"><div class="bar" style="width: 0%"></div></div>                                                                         
      </div>                                                                                                                                          
    </script>                                                                                                                                         
```

```
  $('#track-uploader').S3Uploader                                                                                                                         allow_multiple_files: false                                                                                                                       
    remove_completed_progress_bar: false                                                                                                              
    done: (e, data) ->                                                                                                                                
      console.log("done!")                                                                                                                            
```

**Comment by mcfiredrill** [comment]
I was talking about the `location.href` from this line in jquery-file-upload, which I believe is why I'm POSTing my app's current URL instead of S3.
https://github.com/blueimp/jQuery-File-Upload/blob/master/js/jquery.fileupload.js#L584

**Comment by mcfiredrill** [comment]
Ugh I'm really sorry, looks like I was using the wrong version of the javascript this entire time. It seems to work fine for me.

**Comment by ncri** [comment]
Great! :)
