### ISSUE TITLE
Filepath comes without starting slash on IE

### ISSUE THREAD

**Issue by andreyluiz** [waynehoover/s3_direct_upload#254]
Hi guys.

I'm using s3_direct_upload as follows:

`gem 's3_direct_upload', git: 'https://github.com/waynehoover/s3_direct_upload', ref: '1d633125cf39c04ae30c80f8e1765f21b191b02a'`
#192 is the referenced PR in my Gemfile.

My problem is related to the starting slash in the `filepath` property of the object passed in the callback `s3_upload_complete`.

In Chrome If I try to upload the image Screenshot.png, the returning object will look like this:

``` json
{
  "url": "https://dk9suync0k2va.cloudfront.net/cms%2Ffiles%2F1%2F1473450279Screenshot.png",
  "filepath": "/cms%2Ffiles%2F1%2F1473450279Screenshot.png",
  "filename": "Screenshot.png",
  "filesize": 63731,
  "filetype": "image/png",
  "unique_id": "1uvstno23cbhcr4c"
}
```

Notice the starting slash in the `filepath` property.

If I upload the exact same file in Internet Explorer, the returning object will look like this:

``` json
{
  "url": "https:\/\/dk9suync0k2va.cloudfront.netcms%2Ffiles%2F1%2F1473445422Screenshot.jpg",
  "filepath": "cms%2Ffiles%2F1%2F1473445422Screenshot.jpg",
  "filename": "Screenshot.jpg",
  "filesize": 33394,
  "filetype": "image\/jpeg",
  "unique_id": "xewrzus9pe2u"
}
```

Notice the `filepath` property again. It comes without the starting slash.

Do you guys know if there is a PR where it was fixed?

Thank's.

**Comment by costajohnt** [comment]
I'm noticing this same issue.
