### ISSUE TITLE
CORS troubles

### ISSUE THREAD

**Issue by 303devworks** [waynehoover/s3_direct_upload#30]
Any idea whey I consistently get "Origin http://localhost:3000 is not allowed by Access-Control-Allow-Origin." error on s3?

I've tried several different projects to get this working including the Ryan Bates Screencast and this one: http://pjambet.github.com/blog/direct-upload-to-s3/.  Always the same result.  My app works fine with a standard carrierwave direct upload (so I know my bucket and credentials are ok).  But once I introduce ajax into the mix 100% failure with the error above.

I saw this bug reported: http://code.google.com/p/chromium/issues/detail?id=67743 so I switched from chrome to safari and then firefox.  Same result.  I deleted my bucket and recreated and reset up CORS.  I tried CORS with http://0.0.0.0:3000, http://localhost:3000, \* for the allowed origin.

Any ideas?  Driving me nuts.

**Comment by arthurcolle** [comment]
Where did you put the monkeypatch?

**Comment by fatihtas** [comment]
yeah where to put monkeypatch pls?

**Comment by sheharyarn** [comment]
Just create a new `initializer` in your Rails app:

```ruby
# config/initializers/s3_direct_upload.rb
module S3DirectUpload
  module UploadHelper
    class S3Uploader
      def url
        "http#{@options[:ssl] ? 's' : ''}://#{@options[:bucket]}.#{@options[:region]}.amazonaws.com/"
      end
    end
  end
end
```

**Comment by fatihtas** [comment]
Thanks a lot, I tried, but still getting the 400 BAD request as a response from AWS. 
I also went back to first phase of this and, set up Ryan's 383 version. Still got the 400 Bad request mistake.. 

I guess my problem is either with AWS settings (i did not set up IAM user, using root settings). However, i don't know which type of 400 Bad request i am getting **(Is there a way i can dig in that, i really want to know what type of 400 bad request it is**? ) I tried manually add file on S3 it worked, I tried uploading with carrierwawe it worked. 
However this s3_direct_upload doesn't. 
One other possibility is regarding 2.hours.from_now.utc or 10.hours etc.. I live in Istanbul, using frankfurt region.. shall I try all 1..24.hours.from_now?

**Comment by fatihtas** [comment]
Folks, the problem was because of region selection in my case. Mainly cause of Frankfurt.. it requires signature type v4. 
++ for url alterations u don't need monkey patch, u can use `c.url` field to change it anyway you want. 
just use this version and it works well [https://github.com/RobotsAndPencils/s3_direct_upload ](RobotsAndPencils)
