### ISSUE TITLE
File chunking (More of a question)

### ISSUE THREAD

**Issue by lukebyrne** [waynehoover/s3_direct_upload#88]
Hi Wayne,

Sorry to pollute your issue tracker with this but it is more of a question. I also posted it over the comment thread for the RailsCasts where I found the link to this gem.

Hopefully you may be able to shed some light, otherwise please disregard and delete.

Again sorry for polluting

Cheers

Luke

http://railscasts.com/episodes/383-uploading-to-amazon-s3?view=comments
# 

File chunking.

maxChunkSize: 1000000

I am finding that this directive is working for me. However S3 is not merging the file back together at their end.

I am only getting the last chunked bit of the file appearing in the folder.

I have found this

http://aws.amazon.com/articles/1109?_encoding=UTF8&jiveRedirect=1#14

But am a little unsure what to make of it. Was wondering if anyone else has come across this issue as it is pretty cool feature jquery upload. I am uploading video files and so being able to do it in batches means that their is less chance of file failure.

Hope someone can shed some light.

Kind regards,

Luke
#

**Comment by mdoza** [comment]
@lukebyrne what was the solution. the issue has been 404'd.

**Comment by lukebyrne** [comment]
@mdoza I am sorry but this was over 4 years ago so I cant even remember the context of this thread.

I would recommend looking for another solution, I think in the end I went for something like this service https://www.filestack.com/
